name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up the TERM environment variable
      run: echo "TERM=xterm" >> $GITHUB_ENV

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Build project
      run: make

    - name: Clone tester repository
      run: git clone https://github.com/kichkiro/minishell_tester.git

    - name: Set up tester repository
      run: |
        cd minishell_tester
        pip3 install -r requirements.txt

    - name: Run tests
      run: |
        cd minishell_tester
        python3 src/__main__.py ../
