name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Build project
      run: make

    - name: Clone tester repository
      run: git clone https://github.com/LucasKuhn/minishell_tester.git

    - name: Run tests
      run: |
        cd minishell_tester
        ./tester
