name: Run Minishell Tester

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Clone minishell tester
      run: git clone https://github.com/kichkiro/minishell_tester.git

    - name: Change directory to minishell tester
      run: cd minishell_tester

    - name: Install Python dependencies
      run: |
        cd minishell_tester
        pip3 install -r requirements.txt

    - name: Run minishell tester
      run: |
        cd minishell_tester
        python3 src/__main__.py ../
