name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: https://github.com/Bruno0798/42_libft
    - name: configure
      run: 	make 
    - name: configure
      run: 	git clone https://github.com/LucasKuhn/minishell_tester.git
    - name: configure
      run: 	cd minishell_tester
    - name: configure
      run: ./tester

  
