name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up the TERM environment variable
      run: echo "TERM=xterm" >> $GITHUB_ENV

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Show directory structure before build
      run: |
        echo -e "\033[1;34mListing directory structure before build:\033[0m"
        ls -R

    - name: Build project
      run: |
        echo -e "\033[1;32mBuilding project:\033[0m"
        make

    - name: Show directory structure after build
      run: |
        echo -e "\033[1;34mListing directory structure after build:\033[0m"
        ls -R

    - name: Clone tester repository
      run: |
        echo -e "\033[1;32mCloning tester repository:\033[0m"
        git clone https://github.com/kichkiro/minishell_tester.git

    - name: Set up tester repository
      run: |
        cd minishell_tester
        pip3 install -r requirements.txt
        python3 -m pip install norminette
        pip3 install termcolor  # Ensure termcolor is installed

    - name: Run tests and wait to send input
      run: |
        echo -e "\033[1;32mRunning tests and waiting to send input:\033[0m"
        cd minishell_tester
        echo "2" | python3 src/__main__.py ../
