name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up the TERM environment variable
      run: echo "TERM=xterm" >> $GITHUB_ENV

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Show directory structure before build
      run: |
        echo -e "\033[1;34mListing directory structure before build:\033[0m"
        ls -R

    - name: Build project
      run: |
        echo -e "\033[1;32mBuilding project:\033[0m"
          make

    - name: Clone minishell tester
      run: git clone https://github.com/kichkiro/minishell_tester.git

    - name: Change directory to minishell tester
      run: cd minishell_tester

    - name: Install Python dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Run minishell tester
      run: |
        cd minishell_tester
        python3 src/__main__.py ../
