name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up the TERM environment variable
      run: echo "TERM=xterm" >> $GITHUB_ENV

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Show directory structure before build
      run: |
        echo -e "\033[1;34mListing directory structure before build:\033[0m"
        ls -R

    - name: Build project
      run: |
        echo -e "\033[1;32mBuilding project:\033[0m"
          make

    - name: Clone tester repository
      run: |
        echo -e "\033[1;32mCloning tester repository:\033[0m"
        git clone https://github.com/LucasKuhn/minishell_tester.git

    - name: Set up tester repository
      run: |
        cd minishell_tester

    - name: Run tests
      run: |
        ./tester
